import "pe"

rule packer_win_tiggre
{
    meta:
        author = "Jeff White (karttoon@gmail.com) @noottrak"
        date = "11SEP2018"
        hash1 = "90498f367d20453078df3a75c9dee0a0acc188eb2c571e0f6a94cbd6e7c35494"
        hash2 = "64f90c00f4fad446a41d304b610b0770793b0928914cee705d35856ef7d8431d"
        description = "Detects Tiggre packer" // NAME TEMPORARY - generic AV name

    strings:
        $ = "SetLastError"
        $ = "GetTickCount"
        $ = "ExitProcess"
        $ = "GetStartupInfoA"
        $ = "GetCommandLineA"
        $ = "GetCurrentProcessId"
        $ = "GetCurrentThreadId"
        $ = "GetCurrentProcess"
        $ = "ReadProcessMemory"
        $ = "GetModuleFileNameA"
        $ = "GetModuleHandleA"
        $ = "WriteFile"
        $ = "FreeLibrary"
        $ = "LoadLibraryA"
        $ = "GetProcAddress"
        $ = "DeleteFileW"
        $ = "MoveFileW"
        $ = "CreateFileW"
        $ = "GetFileAttributesW"
        $ = "GetOEMCP"
        $ = "GetProcessHeap"
        $ = "TlsGetValue"
        $ = "TlsSetValue"
        $ = "CreateThread"
        $ = "ExitThread"
        $ = "Sleep"
        $ = "SuspendThread"
        $ = "ResumeThread"
        $ = "TerminateThread"
        $ = "SetThreadPriority"
        $ = "GetThreadPriority"
        $ = "CreateEventA"
        $ = "SetUnhandledExceptionFilter"
        $ = "EnumResourceTypesA"
        $ = "EnumResourceNamesA"
        $ = "EnumResourceLanguagesA"
        $ = "FindResourceA"
        $ = "FindResourceExA"
        $ = "LoadResource"
        $ = "SizeofResource"
        $ = "LockResource"
        $ = "FreeResource"
        $ = "GetWindowsDirectoryA"
        $ = "CopyFileA"
        $ = "CreateProcessA"
        $ = "GetVersionExA"
        $ = "EnumCalendarInfoA"
        $ = "TerminateProcess"
        $ = "GetThreadLocale"
        $ = "SetThreadLocale"
        $ = "GetLastError"
        $ = "GetStdHandle"
        $ = "ReadFile"
        $ = "CloseHandle"
        $ = "SetFilePointer"
        $ = "GetConsoleMode"
        $ = "GetConsoleOutputCP"
        $ = "HeapAlloc"
        $ = "HeapFree"
        $ = "TlsAlloc"
        $ = "LocalAlloc"
        $ = "LocalFree"
        $ = "WaitForSingleObject"
        $ = "ResetEvent"
        $ = "SetEvent"
        $ = "InitializeCriticalSection"
        $ = "DeleteCriticalSection"
        $ = "EnterCriticalSection"
        $ = "LeaveCriticalSection"
        $ = "TryEnterCriticalSection"
        $ = "MultiByteToWideChar"
        $ = "WideCharToMultiByte"
        $ = "GetACP"
        $ = "GetConsoleCP"
        $ = "CompareStringA"
        $ = "GetLocaleInfoA"
        $ = "FormatMessageW"
        $ = "CompareStringW"
        $ = "GetUserDefaultLCID"
        $ = "SysAllocStringLen"
        $ = "SysFreeString"
        $ = "SysReAllocStringLen"
        $ = "MessageBoxA"
        $ = "CharUpperBuffW"
        $ = "CharLowerBuffW"
        $ = "CharUpperA"
        $ = "CharUpperBuffA"
        $ = "CharLowerA"
        $ = "CharLowerBuffA"
        $ = "GetSystemMetrics"
        $ = "MessageBeep"

    condition:
        all of them
          and
        pe.number_of_sections == 7
          and
        pe.number_of_imports == 3
}
